name: app_navigator
description: A Dart/Flutter package for managing app navigation.
version: 1.0.0+1
homepage: https://github.com/Sophaniths-9108-LLC/app_navigator/

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
